pod:
  image: openshift/origin-pod
  container_name: pod
  user: "100000"
  ports:
    - "8080:8080"

mysql:
  image: openshift/mysql-55-centos7
  user: "100000"
  environment:
    MYSQL_ROOT_PASSWORD: mysecretpassword
    MYSQL_DATABASE: liferay
    MYSQL_USER: liferay
    MYSQL_PASSWORD: liferay
  net: "container:pod"

liferay:
  #image: vbehar/liferay-openshift
  build: .
  user: "100000"
  environment:
    LIFERAY_DB_TYPE: MYSQL
    LIFERAY_DB_HOST: localhost
    LIFERAY_DB_DATABASE: liferay
    LIFERAY_DB_USER: liferay
    LIFERAY_DB_PASSWORD: liferay
  net: "container:pod"
